global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:5000'] 

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000'] 
  

